spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@172.168.20.10:1521:orcl
    username: ECARD_V3
    password: ECARD_V3
    validation-query: SELECT 1 FROM DUAL
server:
  port: 9090
